# Generated by Django 5.2.7 on 2025-10-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.FloatField(default=0)),
                ('highest_score', models.FloatField(default=100)),
                ('component_type', models.CharField(choices=[('WW', 'Written Works'), ('PT', 'Performance Tasks'), ('QA', 'Quarterly Assessment')], default='WW', max_length=2)),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='accounts.quarter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='accounts.subject')),
            ],
        ),
    ]
