# Generated by Django 5.2.7 on 2025-10-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_quarter_subject_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='quarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.quarter'),
            preserve_default=False,
        ),
    ]
