# Generated by Django 5.2.7 on 2025-10-30 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subject_quarter'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to=settings.AUTH_USER_MODEL),
        ),
    ]
