# Generated by Django 5.2.7 on 2025-10-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_quarter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
