# Generated by Django 5.2.7 on 2025-11-22 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_goal'),
    ]

    operations = [
    ]
